### ISSUE TITLE
Bug: Cannot find name 'Comment'.

### ISSUE THREAD

**Issue by louis-young-slice** [eslint/css#118]
### Environment

@eslint/css version: v0.7.0

### Which language are you using?

stylesheet

### What did you do?

Imported `@eslint/css` and ran the TypeScript compiler.

### What did you expect to happen?

The TypeScript compiler to not report an error.

### What actually happened?

The TypeScript compiler reported an error.

```shell
> tsc --noEmit

node_modules/@eslint/css/dist/esm/types.ts:34:47 - error TS2304: Cannot find name 'Comment'.

34 export type CSSSyntaxElement = CssNodePlain | Comment;
                                                 ~~~~~~~


Found 1 error in node_modules/@eslint/css/dist/esm/types.ts:34
```

### Link to Minimal Reproducible Example

1. Visit https://codesandbox.io/p/github/louis-young-slice/css-bug-reproduction/main.
2. In the left-hand menu, select the "CodeSandbox" tab.
3. Under "Tasks", click on "type-check" to run the TypeScript compiler.
4. Observe the compiler error in the terminal at the bottom of the screen.

### Participation

- [x] I am willing to submit a pull request for this issue.

### Additional comments

There are two important components here: the version of `@eslint/css` and the project's TypeScript configuration.

The version of `@eslint/css` matters because https://github.com/eslint/css/blob/main/src/types.ts - the problematic module - was introduced by https://github.com/eslint/css/pull/103 and released via https://github.com/eslint/css/pull/111 in v0.7.0.

The TypeScript configuration of the project is relevant due to the nature of the issue. The `types.ts` module exports a [`CSSSyntaxElement` type](https://github.com/eslint/css/blob/main/src/types.ts#L34), which is a union of `CssNodePlain` and `Comment`. [`CssNodePlain` is imported from `@eslint/css-tree`](https://github.com/eslint/css/blob/main/src/types.ts#L12), but `Comment` is not. Instead, it's referring to the [DOM `Comment` interface](https://developer.mozilla.org/en-US/docs/Web/API/Comment), which comes from `node_modules/typescript/lib/lib.dom.d.ts`. This appears to be an oversight - it likely should be imported from `@eslint/css-tree`, just as `CssNodePlain` is. However, [`CssNodePlain` is a union that includes `Comment` as a member](https://github.com/eslint/csstree/blob/main/lib/index.d.ts#L971), making it redundant in the `CSSSyntaxElement` union regardless.

This issue doesn't surface within the `@eslint/css` project due to its [TypeScript configuration](https://github.com/eslint/css/blob/main/tsconfig.json), which relies on the [default `lib` compiler option](https://www.typescriptlang.org/tsconfig/#lib). That default includes the `"dom"` type definitions. However, when you run the TypeScript compiler in a project that does not include the `"dom"` type definitions - for example, a distributable ESLint configuration library - the `Comment` interface is rightly missing, and this causes an error.
